### ISSUE TITLE
Not working :/

### ISSUE THREAD

**Issue by xuru-thor** [ThirteenAG/MaxPayne3.FusionFix#1]
This was working perfectly yesterday, but for some reason now it simply stopped working. Already tried reinstalling this fix, but the skip cutscene promt still shows up.

**Comment by xuru-thor** [comment]
Hello @ThirteenAG, do you have any idea why it could not be working? I really want to replay the game, but the skip cutscene prompt is really annoying.

**Comment by TopDollar86** [comment]
I second this.

The game is infuriating with this stupid prompt in the corner of the cutscenes. Please @ThirteenAG - or anybody - fix this.
