### ISSUE TITLE
Please fix this!

### ISSUE THREAD

**Issue by TopDollar86** [ThirteenAG/MaxPayne3.FusionFix#2]
The latest official patch from Rockstar disables the "HideSkipButton" feature of fusionfix.

The subtitle outlines multiplier still works so whatever is wrong is specific to the skip button.

Please, ThirteenAG - or anybody for that matter - can you fix this? I've searched through every game file in OpenIV trying to find something alluding to the "Press A/Enter" prompt but I can't find anything.

**Comment by ThirteenAG** [comment]
Thanks, should be working now, update the plugin.

**Comment by TopDollar86** [comment]
ThirteenAG, you are a legend!

I was expecting to wait at least a year, possibly never, for you to ever see my post or for it to have any impact, but in less than 24 hours you've fixed it!

And yes, I can confirm the new version does indeed work - finally I can enjoy this game without that stupid prompt in the corner.

Just want to say thank you for doing professional developers' jobs for them. I've used your widescreen patches in other games (the original Max Payne 1 & 2, The Suffering 1 & 2, etc) and you make it possible to enjoy these games on modern hardware. It's fantastic. You really are doing the Lord's work.

P.S if you have any kind of gofundme or paypal address I'd be willing to drop you a small donation for all the aggravation you've saved me over the years.

**Comment by ThirteenAG** [comment]
Thank you for the kind words.
> P.S if you have any kind of gofundme or paypal address I'd be willing to drop you a small donation for all the aggravation you've saved me over the years.
It's on top of wfp page, or inside wfp repo on github, the sponsor button.
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=77JMVFE8N42PE

**Comment by TopDollar86** [comment]
Just dropped you $15. Thanks again for all your work.
