### ISSUE TITLE
[Feature Request] Aspect ratio correction for 16:10 resolutions

### ISSUE THREAD

**Issue by Shockwave508** [ThirteenAG/MaxPayne3.FusionFix#7]
Would it be possible to un-stretch/un-squish the game view and letterbox the FMV's on 16:10 monitors, such as the Steam Deck's own 1280x800 resolution? Normally the game is purely geared to 16:9 resolutions.

**Comment by Tomasak** [comment]
https://github.com/Lyall/MaxPayne3Fix This mod should help you

**Comment by Shockwave508** [comment]
Never knew about this; works perfectly! Issue is safe-to-close.
